// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: M5_clock

#ifndef _M5_CLOCK_UI_H
#define _M5_CLOCK_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_events.h"
void blink_Animation( lv_obj_t *TargetObject, int delay);
void pulse_Animation( lv_obj_t *TargetObject, int delay);
void ui_event_timeScreen( lv_event_t * e);
extern lv_obj_t *ui_timeScreen;
extern lv_obj_t *ui_timeLabel;
extern lv_obj_t *ui_dateText;
extern lv_obj_t *ui_batteryArc;
extern lv_obj_t *ui_chargeIcon;
extern lv_obj_t *ui_minuteText;
extern lv_obj_t *ui_hourText;
extern lv_obj_t *ui_cityText;
extern lv_obj_t *ui_tempText;
extern lv_obj_t *ui_weatherIcon;
void ui_event_messageScreen( lv_event_t * e);
extern lv_obj_t *ui_messageScreen;
extern lv_obj_t *ui_messageIcon;
extern lv_obj_t *ui_messageTitle;
extern lv_obj_t *ui_messageText;
extern lv_obj_t *ui_messageTime;
extern lv_obj_t *ui____initial_actions0;


LV_IMG_DECLARE( ui_img_bolt_png);   // assets\bolt.png
LV_IMG_DECLARE( ui_img_dy2_png);   // assets\dy2.png
LV_IMG_DECLARE( ui_img_whatsapp_png);   // assets\whatsapp.png
LV_IMG_DECLARE( ui_img_alipay_png);   // assets\alipay.png
LV_IMG_DECLARE( ui_img_answer_png);   // assets\answer.png
LV_IMG_DECLARE( ui_img_a_zero_png);   // assets\a_zero.png
LV_IMG_DECLARE( ui_img_back_png);   // assets\back.png
LV_IMG_DECLARE( ui_img_brightness_png);   // assets\brightness.png
LV_IMG_DECLARE( ui_img_camera_png);   // assets\camera.png
LV_IMG_DECLARE( ui_img_clock_round_bg_png);   // assets\clock_round_bg.png
LV_IMG_DECLARE( ui_img_cloudy_png);   // assets\cloudy.png
LV_IMG_DECLARE( ui_img_cloud_bg_png);   // assets\cloud_bg.png
LV_IMG_DECLARE( ui_img_control_png);   // assets\control.png
LV_IMG_DECLARE( ui_img_daysky_png);   // assets\daysky.png
LV_IMG_DECLARE( ui_img_decline_png);   // assets\decline.png
LV_IMG_DECLARE( ui_img_diaphragm_png);   // assets\diaphragm.png
LV_IMG_DECLARE( ui_img_dy0_png);   // assets\dy0.png
LV_IMG_DECLARE( ui_img_dy1_png);   // assets\dy1.png
LV_IMG_DECLARE( ui_img_dy3_png);   // assets\dy3.png
LV_IMG_DECLARE( ui_img_dy4_png);   // assets\dy4.png
LV_IMG_DECLARE( ui_img_dy5_png);   // assets\dy5.png
LV_IMG_DECLARE( ui_img_dy6_png);   // assets\dy6.png
LV_IMG_DECLARE( ui_img_dy7_png);   // assets\dy7.png
LV_IMG_DECLARE( ui_img_facebook_png);   // assets\facebook.png
LV_IMG_DECLARE( ui_img_hour_h_png);   // assets\hour_h.png
LV_IMG_DECLARE( ui_img_hour_tr_png);   // assets\hour_tr.png
LV_IMG_DECLARE( ui_img_info_png);   // assets\info.png
LV_IMG_DECLARE( ui_img_instagram_png);   // assets\instagram.png
LV_IMG_DECLARE( ui_img_ios_back_png);   // assets\ios_back.png
LV_IMG_DECLARE( ui_img_kakao_png);   // assets\kakao.png
LV_IMG_DECLARE( ui_img_1592976543);   // assets\left-arrow.png
LV_IMG_DECLARE( ui_img_line_png);   // assets\line.png
LV_IMG_DECLARE( ui_img_mail_png);   // assets\mail.png
LV_IMG_DECLARE( ui_img_mask_png);   // assets\mask.png
LV_IMG_DECLARE( ui_img_meet_png);   // assets\meet.png
LV_IMG_DECLARE( ui_img_messenger_png);   // assets\messenger.png
LV_IMG_DECLARE( ui_img_microphone_png);   // assets\microphone.png
LV_IMG_DECLARE( ui_img_minute_tr_png);   // assets\minute_tr.png
LV_IMG_DECLARE( ui_img_next_png);   // assets\next.png
LV_IMG_DECLARE( ui_img_nightsky_png);   // assets\nightsky.png
LV_IMG_DECLARE( ui_img_notify_png);   // assets\notify.png
LV_IMG_DECLARE( ui_img_nt0_png);   // assets\nt0.png
LV_IMG_DECLARE( ui_img_nt1_png);   // assets\nt1.png
LV_IMG_DECLARE( ui_img_nt2_png);   // assets\nt2.png
LV_IMG_DECLARE( ui_img_nt3_png);   // assets\nt3.png
LV_IMG_DECLARE( ui_img_nt4_png);   // assets\nt4.png
LV_IMG_DECLARE( ui_img_nt5_png);   // assets\nt5.png
LV_IMG_DECLARE( ui_img_nt6_png);   // assets\nt6.png
LV_IMG_DECLARE( ui_img_nt7_png);   // assets\nt7.png
LV_IMG_DECLARE( ui_img_pause_png);   // assets\pause.png
LV_IMG_DECLARE( ui_img_paypal_png);   // assets\paypal.png
LV_IMG_DECLARE( ui_img_penguin_png);   // assets\penguin.png
LV_IMG_DECLARE( ui_img_photo_png);   // assets\photo.png
LV_IMG_DECLARE( ui_img_play_png);   // assets\play.png
LV_IMG_DECLARE( ui_img_qr_png);   // assets\qr.png
LV_IMG_DECLARE( ui_img_2138854088);   // assets\right-arrow.png
LV_IMG_DECLARE( ui_img_search_png);   // assets\search.png
LV_IMG_DECLARE( ui_img_second_h_png);   // assets\second_h.png
LV_IMG_DECLARE( ui_img_second_tr_png);   // assets\second_tr.png
LV_IMG_DECLARE( ui_img_setting_png);   // assets\setting.png
LV_IMG_DECLARE( ui_img_skype_png);   // assets\skype.png
LV_IMG_DECLARE( ui_img_sms_png);   // assets\sms.png
LV_IMG_DECLARE( ui_img_sun_png);   // assets\sun.png
LV_IMG_DECLARE( ui_img_teams_png);   // assets\teams.png
LV_IMG_DECLARE( ui_img_telegram_png);   // assets\telegram.png
LV_IMG_DECLARE( ui_img_timeout_png);   // assets\timeout.png
LV_IMG_DECLARE( ui_img_twitter_png);   // assets\twitter.png
LV_IMG_DECLARE( ui_img_up_arrow_png);   // assets\up_arrow.png
LV_IMG_DECLARE( ui_img_viber_png);   // assets\viber.png
LV_IMG_DECLARE( ui_img_vkontakte_png);   // assets\vkontakte.png
LV_IMG_DECLARE( ui_img_weather_bg_png);   // assets\weather_bg.png
LV_IMG_DECLARE( ui_img_wechat_png);   // assets\wechat.png
LV_IMG_DECLARE( ui_img_wechat_pay_png);   // assets\wechat_pay.png
LV_IMG_DECLARE( ui_img_weibo_png);   // assets\weibo.png


LV_FONT_DECLARE( ui_font_bolld_100);
LV_FONT_DECLARE( ui_font_Font1);
LV_FONT_DECLARE( ui_font_regular100);
LV_FONT_DECLARE( ui_font_regular_120);
LV_FONT_DECLARE( ui_font_semi100);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
